apiVersion: v1
kind: Pod
metadata:
  name: private-reg-pod
  namespace: awesomeapps
spec:
  containers:
    - name: foo
      image: janedoe/awesomeapp:v1
  imagePullSecrets:
    - name: private-reg-cred