---
apiVersion: v1
kind: Pod
metadata:
  name: my-web-server
  namespace: default
spec:
  serviceAccountName: dashboard-sa
  containers:
  - name: my-container
    image: nginx

---
#kubectl run new-pod --image=nginx --namespace=default --as=system:serviceaccount:default:dashboard-sa
