apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign-pods-to-nodes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx
      nodeSelector:
        environment: production
