apiVersion: apps/v1
kind: Deployment
metadata:
  name: In-Operator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: environment
                  operator: In
                  values:
                  - production
                - key: type
                  operator: In
                  values:
                  - compute
              topologyKey: kubernetes.io/hostname
