apiVersion: apps/v1
kind: Deployment
metadata:
  name: DoesNotExist-Operator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: environment
                operator: DoesNotExist
            topologyKey: kubernetes.io/hostname
