apiVersion: apps/v1
kind: Deployment
metadata:
  name: stu-mnm-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stu-mnm-be  
  template:
    metadata:
      labels:
        app: stu-mnm-be
    spec:
      containers:
      - name: stu-mnm-be
        image: nasirnjs/stumnmbe:0.0.7
        ports:
        - containerPort: 80
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-st-svc:3306/studentdb?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-app-user
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-app-user
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: stu-mnm-be
spec:
  selector:
    app: stu-mnm-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080